version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel-network
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel-network
  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge
